theme: jekyll-theme-cayman
title: Social Context Workshop
description: "Towards Responsibly Infusing NLP With Social Context, Community Meanings, and Pragmatics Through Interdisciplinary NLP Efforts."
basepath: ""


navigation:
- text: HOME
  url: /
- text: PROGRAM
  url: /program.html
  layout: post
- text: ORGANIZERS
  url: /organizers.html  
- text: AI4DEV
  url: /ai4dev.html  
- text: DATES
  url: /dates.html
  layout: project
- text: CALL FOR PAPERS
  url: /cfp.html

